paths:

  /products/{id}:

    get:
      summary: Get product by id
      tags:
        - Product
      parameters:
        - in: path
          name: id
          schema:
            type: string
      responses:
        200:
          description: Product found
        404:
          description: Product not found
        500:
          description: Some server error

    delete:
      summary: Delete product by id
      tags:
        - Product
      parameters:
        - in: path
          name: id
          schema:
            type: string
      responses:
        200:
          description: Product found and deleted
        404:
          description: Product not found
        500:
          description: Some server error

  /products/all:

    get:
      summary: Get all products
      tags:
        - Product
      responses:
        200:
          description: Product list
        500:
          description: Some server error

  /products:

    post:
      summary: Create new product
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LMProduct"
      responses:
        201:
          description: Product created
        500:
          description: Some server error

    put:
      summary: Update product
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LMProduct"
      responses:
        200:
          description: Product updated
        404:
          description: Product not found
        500:
          description: Some server error

