version: "3"
services:

  kn-utils-server:
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - 3003:3001
    command: "npm run start"

  kn-utils-db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_ROOT}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"

networks:
  kn-net:
    driver: bridge
