version: "3"
services:

  kn-utils-server:
    image: "node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 3003:3001
    command: "npm run start"

  kn-utils-db:
    image: mongo:latest
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "lionmiss-admin"
      MONGO_INITDB_ROOT_PASSWORD: ";QVuV1as7OBN%-]"
      MONGO_INITDB_DATABASE: "lionmiss"

networks:
  kn-net:
    driver: bridge
