components:
  schemas:
    Size:
      type: string
      enum:
        - xs
        - s
        - m
        - l
        - xl
        - xxl
    Color:
      type: string
      enum:
        - red
        - orange
        - yellow
        - green
        - aqua
        - blue
        - purple
        - pink
        - white
        - black
    PromoType:
      type: string
      enum:
        - Percent
        - Qty
      properties:
        key:
          type: string
        value:
          type: string
    Promo:
      type: object
      required:
        - type
        - qty
      properties:
        type:
          $ref: '#/components/schemas/PromoType'
        qty:
          type: number
    ProductProps:
      type: object
      required:
        - key
        - value
      properties:
        key:
          type: string
        value:
          type: string
    Country:
      type: object
      required:
        - name
        - nameCode
        - currency
        - currencyName
      properties:
        name:
          type: string
        nameCode:
          type: string
        currency:
          type: string
        currencyName:
          type: string
    Img:
      type: object
      required:
        - src
        - title
        - alt
        - main
      properties:
        _id:
          type: string
        src:
          type: string
        title:
          type: number
        alt:
          type: string
        main:
          type: boolean
    Product:
      type: object
      required:
        - name
        - price
        - description
        - details
        - colors
        - unds
        - imgs
      properties:
        _id:
          type: string
        name:
          type: string
        price:
          type: number
        description:
          type: string
        details:
          $ref: '#/components/schemas/ProductProps'
        colors:
          $ref: '#/components/schemas/Color'
        imgs:
          $ref: '#/components/schemas/Img'
    Cart:
      type: object
      required:
        - products
        - taxes
      properties:
        _id:
          type: string
        products:
          type: array
          items:
            type: object
        promo:
          type: object
        taxes:
          type: number
    CartProduct:
      type: object
      required:
        - size
        - unds
        - product
      properties:
        _id:
          type: string
        size:
          $ref: '#/components/schemas/Size'
        color:
          $ref: '#/components/schemas/Color'
        unds:
          type: number
        product:
          $ref: '#/components/schemas/Product'
    CreditCard:
      type: object
      required:
        - creditNumber
        - fullName
        - month
        - year
        - cvv
      properties:
        _id:
          type: string
        creditNumber:
          type: number
        fullName:
          type: string
        month:
          type: number
        year:
          type: number
        cvv:
          type: number
    Measures:
      type: object
      required:
        - chest
        - waist
        - hip
      properties:
        chest:
          type: number
        waist:
          type: number
        hip:
          type: number
        size:
          $ref: '#/components/schemas/Size'
    PropsBuy:
      type: object
      required:
        - productId
        - qty
      properties:
        productId:
          type: string
        color:
          t$ref: '#/components/schemas/Size'
        size:
          $ref: '#/components/schemas/Size'
        qty:
          type: number
    Address:
      type: object
      required:
        - name
        - adderss
        - country
        - state
        - town
        - zip
        - phone
        - mail
        - comments
        - main
      properties:
        _id:
          type: string
        name:
          type: string
        adderss:
          type: string
        country:
          type: string
        state:
          type: string
        town:
          type: string
        zip:
          type: string
        phone:
          type: string
        mail:
          type: string
        comments:
          type: string
        main:
          type: boolean
    User:
      type: object
      required:
        - username
        - avatar
        - lang
        - currency
        - measures
        - email
        - addresses
      properties:
        username:
          type: string
        avatar:
          $ref: '#/components/schemas/Size'
        lang:
          $ref: '#/components/schemas/Color'
        currency:
          type: number
        measures:
          $ref: '#/components/schemas/Measures'
        email:
          $ref: '#/components/schemas/Product'
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
    Comment:
      type: object
      required:
        - comment
        - date
        - ratting
        - measures
        - user
        - imgs
      properties:
        _id:
          type: string
        comment:
          type: '#/components/schemas/Size'
        date:
          type: string
        ratting:
          type: number
        measures:
          $ref: '#/components/schemas/Measures'
        user:
          $ref: '#/components/schemas/User'
        imgs:
          type: array
          items:
            $ref: '#/components/schemas/Img'
    Shipping:
      type: object
      required:
        - initDate
        - finishDate
        - priceShipping
        - shippingMethod
        - paymentMethod
        - cart
      properties:
        _id:
          type: string
        initDate:
          type: string
        finishDate:
          type: string
        priceShipping:
          type: number
        shippingMethod:
          type: string
        paymentMethod:
          type: string
        cart:
          $ref: '#/components/schemas/Cart'